(deftheme jw-purple-haze
  "Created 2013-10-01.")

(custom-theme-set-faces
 'jw-purple-haze
 '(default ((t (:family "default" :foundry "default" :width normal :height 1 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#fff" :background "#000" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#ffffff" :background "#d96e26"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#d96e26" :background "#211d3c"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#606a92"))))
 '(highlight ((t (:background "#503450"))))
 '(region ((t (:background "#1F102f"))))
 '(shadow ((t (:foreground "#999999"))))
 '(secondary-selection ((t (:background "#444083"))))
 '(trailing-whitespace ((t (:background "#ff0000"))))
 '(font-lock-builtin-face ((t (:foreground "#606590"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7078a2" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#505f89"))))
 '(font-lock-constant-face ((t (:foreground "#9a99e7"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#8083be"))))
 '(font-lock-keyword-face ((t (:foreground "#aa8da7"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#a0adee"))))
 '(font-lock-type-face ((t (:foreground "#5f5e8a"))))
 '(font-lock-variable-name-face ((t (:foreground "#8e8eb8"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#FF0000" :inherit (error)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#a069aa"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#506080" :background "#111111"))))
 '(header-line ((t (:underline (:color foreground-color :style line) :inverse-video nil :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#FFFFFF" :background "#5f5e8a"))))
 '(mode-line ((t (:background "#444444" :foreground "#dddddd" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold :box nil))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box nil))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "grey40" :style nil) :foreground "#777777" :background "#111111" :inherit (mode-line)))))
 '(isearch ((t (:foreground "white" :background "#5533AA"))))
 '(isearch-fail ((t (:foreground "#000000" :background "#880000"))))
 '(lazy-highlight ((t (:foreground "#CCCCCC" :background "#331144"))))
 '(match ((t (:foreground "white" :background "#5c2e7a"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'jw-purple-haze)
